; File di configurazione di esempio per l'esercizio 2 della lezione 3.4.
; Applicazione fittizia; nessun dato reale.
[rete]
server = 192.168.10.20
porta = 8080

[wifi_ospiti]
ssid = Scuola-Ospiti
; la password e' "protetta" per non essere leggibile a colpo d'occhio
password_b64 = UGFzc3dvcmQgZGVsIFdpLUZpIG9zcGl0aTogQXVsYS1NYWduYS0yMDI2
